apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: vpug60kw1-python 
  janus-idp.io/tekton: vpug60kw1-python
  backstage.io/kubernetes-id: vpug60kw1-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: vpug60kw1-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml